### ISSUE TITLE
When runnin the test example, I get the following warning

### ISSUE THREAD

**Issue by Rohit-Satyam** [patrickbryant1/SpeedPPI#29]
When I run speedppi with Uniref_30 database, I get the following warning
```
- 23:11:17.538 WARNING: Warning in /big/martin/hh-suite/src/hhalignment.cpp:3518: MergeMasterSlave:

- 23:11:17.538 WARNING: 	maximum number of 65535 sequences exceeded while reading UniRef100_A0A444GEQ0. Skipping all following sequences of this MSA

```

Besides, if we have large number of proteins is there a way to skip AlphaFold predictions and use the PDBs from Alphafold database?

**Comment by Rohit-Satyam** [comment]
And the pipeline fails with the following error:
```bash
Running pred 1 out of 5
/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
Traceback (most recent call last):
  File "/phd/project2/tools/SpeedPPI/./src/run_alphafold_all_vs_all.py", line 37, in <module>
    from alphafold.model import config
  File "/phd/project2/tools/SpeedPPI/src/alphafold/model/config.py", line 18, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'
Running pred 2 out of 5
/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
Traceback (most recent call last):
  File "/phd/project2/tools/SpeedPPI/./src/run_alphafold_all_vs_all.py", line 37, in <module>
    from alphafold.model import config
  File "/phd/project2/tools/SpeedPPI/src/alphafold/model/config.py", line 18, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'
Running pred 3 out of 5
/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
Traceback (most recent call last):
  File "/phd/project2/tools/SpeedPPI/./src/run_alphafold_all_vs_all.py", line 37, in <module>
    from alphafold.model import config
  File "/phd/project2/tools/SpeedPPI/src/alphafold/model/config.py", line 18, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'
Running pred 4 out of 5
/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
Traceback (most recent call last):
  File "/phd/project2/tools/SpeedPPI/./src/run_alphafold_all_vs_all.py", line 37, in <module>
    from alphafold.model import config
  File "/phd/project2/tools/SpeedPPI/src/alphafold/model/config.py", line 18, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'
Running pred 5 out of 5
/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
Traceback (most recent call last):
  File "/phd/project2/tools/SpeedPPI/./src/run_alphafold_all_vs_all.py", line 37, in <module>
    from alphafold.model import config
  File "/phd/project2/tools/SpeedPPI/src/alphafold/model/config.py", line 18, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'
Traceback (most recent call last):
  File "/phd/project2/tools/SpeedPPI/./src/build_ppi.py", line 32, in <module>
    ppi_net = pd.concat(all_ppis)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/speed_ppi/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
mv: cannot stat './data/test/all_vs_all//pred*/*.pdb': No such file or directory
Moved all high confidence predictions to ./data/test/all_vs_all//high_confidence_preds/

```

I downloaded the Alphafold params from:  https://storage.googleapis.com/alphafold/alphafold_params_2022-12-06.tar
```
./create_ppi_all_vs_all.sh data/test/test.fasta /home/subudhak/phddata/project2/tools/SpeedPPI/hh-suite/bin/hhblits 0.5 ./data/test/all_vs_all/
```

**Comment by Rohit-Satyam** [comment]
Resolved by installing `ml_collections`
